version: '3'
services:
  mynode1:
    container_name: mynode1 
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3001:3000"
    command: npm run start-dev
    